# Generated by Django 6.0.2 on 2026-02-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
